Feat/ubi 25 back criar os models
PROJECT-UBI/projeto_ubi_backend pull request #2
Opened 2024-04-09 19:05 UTC by GabrielPereiraCampos

Favor verificar se as Models e relacionamentos estão corretos e validar o PR

2024-04-10 03:57 UTC, junionestor requested changes
Verificar os relacionamentos em [diagrama banco de dados](https://lucid.app/lucidchart/a55fe139-20c4-4c9e-a44f-1a1a3e5a4098/edit?invitationId=inv_91b9fc58-3ce2-485c-a27a-c2b18fe688aa&page=0_0#) e corrigir as falhas de relacionamentos nos Models.

2024-04-10 11:38 UTC, GabrielPereiraCampos commented
Mudanças feitas seguindo a documentação do Laravel

2024-04-10 12:39 UTC, junionestor requested changes

2024-04-10 12:39 UTC, junionestor commented on app/Models/MedicalRecord.php
> +        return $this->belongsToMany(User::class);
o padrão do laravel segue a ordem alfabética dos nomes das tabelas, esse trecho espera uma tabela chamada medical_record_user

2024-04-10 12:39 UTC, junionestor commented on app/Models/User.php
> +    public function medical_recordss(): BelongsToMany
nome de função em desacordo com os padrões

2024-04-10 12:39 UTC, junionestor commented on app/Models/Responsible.php
> +    public function medical_records(): BelongsToMany
nome de função em desacordo com os padrões

2024-04-10 12:39 UTC, junionestor commented on app/Models/Band.php
> +    public function medical_records(): BelongsTo
nome de função em desacordo com os padrões

2024-04-10 12:50 UTC, GabrielPereiraCampos commented on app/Models/User.php
> +    public function medical_recordss(): BelongsToMany
Vou corrigir o nome, foi um "s" a mais.

2024-04-10 12:51 UTC, GabrielPereiraCampos commented on app/Models/Responsible.php
> +    public function medical_records(): BelongsToMany
O padrão não é o nome do model que vai relacionar no plural? Olhei na documentação e todos os exemplos o nome da função esta no plural

2024-04-10 12:52 UTC, GabrielPereiraCampos commented on app/Models/MedicalRecord.php
> +        return $this->belongsToMany(User::class);
Vou corrigir.

2024-04-10 12:53 UTC, GabrielPereiraCampos commented on app/Models/Band.php
> +    public function medical_records(): BelongsTo
O padrão não é o nome do model que vai relacionar no plural? Olhei na documentação e todos os exemplos o nome da função esta no plural

2024-04-10 14:44 UTC, junionestor commented on app/Models/MedicalRecord.php
> +        return $this->belongsToMany(User::class);
favor realizar os testes

2024-04-10 14:44 UTC, junionestor commented on app/Models/Responsible.php
> +    public function medical_records(): BelongsToMany
favor verificar

2024-04-10 14:44 UTC, junionestor commented on app/Models/Band.php
> +    public function medical_records(): BelongsTo
favor verificar

2024-04-12 11:22 UTC, GabrielPereiraCampos commented
Nome das funções medicalRecords de acordo com o padrão camel case

2024-04-12 15:09 UTC, junionestor requested changes
![image](https://github.com/PROJECT-UBI/projeto_ubi_backend/assets/23237439/c8c66712-88ac-41a0-9841-bc26fdb1f2e7)
favor realizar testes

2024-04-12 17:10 UTC, GabrielPereiraCampos commented
A tabela não tem "ubi." no nome, na relação eu dei o nome medical_record_user, só testa se é isso pf.
Se não for amanhã eu vejo.

2024-04-13 20:28 UTC, junionestor requested changes
favor realizar os testes antes de subir, algum relacionamento ou nome de tabela não está correto.
![image](https://github.com/PROJECT-UBI/projeto_ubi_backend/assets/23237439/d2ee120e-5dfe-4829-aa16-4d47b0b19b7b)

2024-04-14 19:02 UTC, junionestor requested changes

2024-04-14 19:02 UTC, junionestor commented on app/Models/Responsible.php
> +        return $this->belongsToMany(MedicalRecord::class, 'medical_record_responsible','responsible_id','medical_record_id');
Linha com mais de 120 caracteres.

2024-04-14 19:02 UTC, junionestor commented on app/Models/MedicalRecord.php
> +        return $this->belongsToMany(Responsible::class, 'medical_record_responsible','medical_record_id','responsible_id');
Linha com mais de 120 caracteres.

2024-04-14 21:41 UTC, GabrielPereiraCampos commented
Melhorias aplicadas.

2024-04-14 21:42 UTC, GabrielPereiraCampos commented on app/Models/MedicalRecord.php
> +        return $this->belongsToMany(Responsible::class, 'medical_record_responsible','medical_record_id','responsible_id');
Corrigido.

2024-04-14 21:42 UTC, GabrielPereiraCampos commented on app/Models/Responsible.php
> +        return $this->belongsToMany(MedicalRecord::class, 'medical_record_responsible','responsible_id','medical_record_id');
Corrigido.

2024-04-15 23:32 UTC, junionestor approved these changes

2024-04-15 23:33 UTC, merged